services:
  app:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://schedule_app_db:5432/schedule_app_db"
    depends_on:
     - schedule_app_db
    ports:
     - "8080:8080"
  schedule_app_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: schedule_app_db
    volumes:
      - schedules-app-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  schedules-app-data:
